### ISSUE TITLE
run sort order?

### ISSUE THREAD

**Issue by evantrillium** [BlinkTagInc/gtfs-to-html#95]
@brendannee we occassionally run into an issue where the runs appear out of order, and there doesn't appear to be a logic to it (or a way to override how g2h orders runs)

Current issue
http://yartsstaging.wpengine.com/routes-and-schedules/merced-hwy-140/
see attached raw html file and config

you'll see that 140-10 Mon-Sun comes first, even though it should be second to last.

These tts were generated using the old mongod gtfs-to-html.
[config.txt](https://github.com/BlinkTagInc/gtfs-to-html/files/5419162/config.txt)
[3890_merced-hwy-140_1_mon-sun.txt](https://github.com/BlinkTagInc/gtfs-to-html/files/5419165/3890_merced-hwy-140_1_mon-sun.txt)

Anything you can spot that would cause this behavior?

**Comment by brendannee** [comment]
Thanks for reporting this issue.

I pushed an improvement to how trip order is determined by finding a common stop which solves the ordering issue for this route. This is in GTFS-to-HTML version 1.1.1.

Let me know if this works for you.

**Comment by evantrillium** [comment]
thanks @brendannee - I will have my team review and let you know if we're able to utilize the new version to resolve the issue.

**Comment by danielleogden** [comment]
Hello @brendannee! Unfortunately, we are still seeing this issue with runs out of order. One of our colleagues recently tried running gtfs2html using your default template, the trillium template, and the pvvta template and runs were runs out of order.  

I've attached the schedule and the output html timetable for your reference. Let me know if you need anything else to address this issue.
[PVVTA_rt4.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/5539411/PVVTA_rt4.zip)

**Comment by danielleogden** [comment]
@brendannee Hi Brendan, just checking in to see if you've had time to review this issue. Is this something you'll have time to address this week?

**Comment by brendannee** [comment]
Hi,

I just ran this GTFS http://data.trilliumtransit.com/gtfs/paloverde_valley-ca-us/paloverde_valley-ca-us.zip with gtfs-to-html version 1.3.1 and got the correct sort order.  Here is the output I got:  
[pvvta.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/5550826/pvvta.zip)

Check that you are using  GTFS-to-HTML version 1.1.1 or above (preferably the latest 1.3.1). If you installed via npm, you can run:

    npm uninstall -g gtfstohtml

    npm install -g gtfstohtml

to be sure you've got the latest version.

**Comment by danielleogden** [comment]
Thanks @brendannee ! Our dev reinstalled and is now getting the correct output.
